name: monika
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libprotobuf=3.20.3=he621ea3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - mpi=1.0=mpich
  - mpi4py=3.1.4=py39hfc96bbd_0
  - mpich=3.3.2=hc856adb_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3=py39h06a4308_0
  - protobuf=3.20.3=py39h6a678d5_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py39h06a4308_0
  - xlrd=2.0.1=pyhd3eb1b0_1
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - alembic==1.12.1
      - appdirs==1.4.4
      - asttokens==2.2.1
      - attrs==23.1.0
      - backcall==0.2.0
      - bel-resources==0.0.3
      - black==18.6b4
      - certifi==2022.12.7
      - cffi==1.16.0
      - charset-normalizer==3.1.0
      - click==8.1.7
      - click-plugins==1.1.1
      - colorlog==6.7.0
      - comm==0.1.3
      - cycler==0.11.0
      - cython==3.0.4
      - debugpy==1.6.7
      - decorator==5.1.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.1.3
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - fbpca==1.0
      - fonttools==4.39.3
      - greenlet==3.0.1
      - idna==3.4
      - igraph==0.10.4
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - iniconfig==2.0.0
      - ipykernel==6.22.0
      - ipython==8.13.1
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.17.3
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - kiwisolver==1.4.4
      - leidenalg==0.9.1
      - lxml==4.9.3
      - mako==1.2.4
      - markupsafe==2.1.3
      - matplotlib==3.4.3
      - matplotlib-inline==0.1.6
      - multisplitby==0.0.1
      - mypy-extensions==1.0.0
      - natsort==8.3.1
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - networkx==3.2.1
      - nose==1.3.7
      - numpy==1.26.1
      - numpy-groupies==0.9.20
      - openpyxl==3.1.2
      - optuna==3.4.0
      - packaging==23.1
      - pandas==2.0.1
      - parso==0.8.3
      - pathspec==0.11.2
      - patsy==0.5.3
      - pexpect==4.8.0
      - pickle5==0.0.11
      - pickleshare==0.7.5
      - pillow==9.5.0
      - platformdirs==3.5.0
      - pluggy==1.3.0
      - progressbar==2.5
      - progressbar33==2.4
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pybel==0.13.2
      - pycparser==2.21
      - pygments==2.15.1
      - pygsp==0.5.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - pytest==7.4.3
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0.1
      - pyzmq==25.0.2
      - requests==2.29.0
      - requests-file==1.5.1
      - rpy2==3.5.14
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - session-info==1.0.0
      - six==1.15.0
      - smart-open==6.4.0
      - stack-data==0.6.2
      - statsmodels==0.13.5
      - stdlib-list==0.9.0
      - tabulate==0.7.5
      - tenacity==8.2.2
      - texttable==1.6.7
      - threadpoolctl==3.2.0
      - toml==0.10.2
      - tomli==2.0.1
      - tornado==6.3.1
      - tqdm==4.65.0
      - traitlets==5.9.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - tzlocal==5.2
      - urllib3==1.26.15
      - wcwidth==0.2.6
      - zipp==3.15.0
prefix: path/to/anaconda3/envs/monika 
